---
title: "2023_Beebei_Revamp"
author: "Chloe Fouilloux"
date: '2023-04-19'
output: html_document
---

I am here for the journey! It is very exciting to be revising these data with a big more statistical prowess in my pocket. Let's see what this whole dataset it all about. 

```{r Libraries}

library(ggplot2)
library(tidyverse)
library(DHARMa)
library(glmmTMB)
library(readxl)
library(forcats)
library(ggdist)
library(sjPlot)

library(stringr)
library(gridExtra)
library(AICcmodavg)
```

Great, now let's load up out **data file**. 

```{r Data Load + Wrangling}

#Say hello to our little friend!

goop<- read.csv("Beebei_PoolData2023.csv") %>%
        mutate(Bromeliad = as.factor(Bromeliad), 
               Water = as.factor(Water), 
               L_H = as.factor(L_H),
               Goop_Cat = as.factor(Goop_Cat)) 

#Getting factor levels cleaned up
goop$L_H<- forcats::fct_relevel(goop$L_H, "Low", "Middle", "High")
goop$Goop_Cat <- forcats::fct_relevel(goop$Goop_Cat,"None", "Low", "Medium", "High")

```

Let's look a bit at what's up here.
```{r Theme Set}
theme_set(  theme(legend.position = "none",
                  strip.background = element_rect(fill = "White"),
                  panel.background = element_rect(fill = "white",
                                                  colour = "black"), 
                  panel.grid.major = element_blank(), 
                  panel.grid.minor = element_blank(), 
                  text = element_text(size = 14)))
```

Descriptive statistics table

```{r Descriptive Stats Table}

#Reviewer request that only looks at presence/absence data

descrip_stats_YN <- goop %>%
                tidyr::drop_na() %>%
                group_by(YNTad)%>%
                dplyr::select(Temp, DO, Depth, Width, Volume, logPAR, 
                              Goop_Count)%>%
                dplyr::summarise(mean(Temp),sd(Temp), mean(DO), sd(DO),
                                 mean(Goop_Count),sd(Goop_Count),
                                mean(Width), sd(Width),
                                mean(Volume), sd(Volume),
                                mean(Depth), sd(Depth), mean(logPAR), 
                                sd(logPAR)) 
```

Alright, let's get to some modelling!

```{r Models}

######## ######## ######## ######## ######## ######## ######## 
######## Tad presence predicted by goop level and leaf height ################
######## ######## ######## ######## ######## ######## ########

#Tadpole status YN predicted by pool abiotic factors

m1a<- glmmTMB(YNTad ~ Water + DO + Temp + logPAR + Goop_Count + Depth +Volume + L_H + (1|Bromeliad), data = goop, family = binomial)
summary(m1a)
step(m1a)


#Ideal AIC generated by stepwise procedure
m1b<- glmmTMB(YNTad ~ Temp + Goop_Count + Depth + L_H + (1|Bromeliad), data = goop, family = binomial)
summary(m1b)


#############################
#checking others to see behaviour change of stepwise model change

m1c<- glmmTMB(YNTad ~ Temp + Goop_Count + Depth + L_H + Volume + (1|Bromeliad), data = goop, family = binomial)

m1d<- glmmTMB(YNTad ~ Water + DO + Temp + Goop_Count + Depth + L_H + Volume + (1|Bromeliad), data = goop, family = binomial)

m1e<- glmmTMB(YNTad ~ Water +  Temp + Goop_Count + Depth + L_H + Volume + (1|Bromeliad), data = goop, family = binomial)
summary(m1e)

#AIC SUMMARY TABLE----
aic.cand<- list(m1a,
         m1b, 
         m1c, 
         m1d, 
         m1e)
Cand.names <- c( "m1a",
         "m1b", 
         "m1c", 
         "m1d", 
         "m1e") 
aictab(aic.cand, Cand.names, sort = T) #here we see m1b is the best fit, let's check it out

#run these two lines together
simulationOutput <- simulateResiduals(fittedModel = m1b)
plot(simulationOutput)
#
testDispersion(m1b)
testZeroInflation(m1b)

tab_model(m1b, 
          transform = NULL,
          show.ci = F, 
          show.est = T, 
          show.se = T, 
          show.stat = T,
          show.obs = F,
          show.r2 = F,
          string.stat = "z value",
          string.se = "SE", 
          dv.labels = "Predictors of tadpole occurence",
          pred.labels = c("(Intercept)",
                          "Temperature",
                          "Mucilage level (0-3)", 
                          "Depth", 
                          "Leaf height: Medium",
                          "Leaf height: High"))


######## ######## ######## ######## ######## ######## ######## ######## 
######## **There are more tadpoles in goopy pools, but what do these pools look like?** ########
######## Goop Modelling: What do goopy pools look like? ################
######## ######## ######## ######## ######## ######## ########

m2a<- glmmTMB(Goop_Count ~ Water + DO + Temp + logPAR + Depth+ Volume + L_H + (1|Bromeliad), data = goop, family = poisson)

#RE: Error message. This warning occurs when the optimizer visits a region of parameter space that is invalid. It is not a problem as long as the optimizer has left that region of parameter space upon convergence, which is indicated by an absence of the model convergence warnings described above.
step(m2a)

######################
m2b<- glmmTMB(Goop_Count ~ Water + DO + Temp + logPAR + Depth+ Volume + (1|Bromeliad), data = goop, family = poisson)
m2c<- glmmTMB(Goop_Count ~ Water + DO + Temp + logPAR + Depth + (1|Bromeliad), data = goop, family = poisson)
m2d<- glmmTMB(Goop_Count ~ Water + DO + logPAR + Depth + (1|Bromeliad), data = goop, family = poisson)
m2e<- glmmTMB(Goop_Count ~ Water + DO + logPAR + (1|Bromeliad), data = goop, family = poisson) #ALERT: THIS MODEL HAS THE LOWEST AIC, BUT HAS PATTERNS IN THE RESIDUALS, SO WE WILL GO WITH M2D WHICH IS WIHTIN 2AIC. :-) 

#AIC SUMMARY TABLE----
aic.cand<- list(m2a,
         m2b, 
         m2c, 
         m2d, 
         m2e)
Cand.names <- c( 
         "m2a",
         "m2b", 
         "m2c", 
         "m2d", 
         "m2e") 
aictab(aic.cand, Cand.names, sort = T)


#Model with the lowest AIC that also passes DHARMa checks were chosen. The significant variables from the final model were identical to the core model. 

#RUN TWO LINES TOGETHER
simulationOutput <- simulateResiduals(fittedModel = m2d)
plot(simulationOutput)

testDispersion(m2d)
testZeroInflation(m2d)

tab_model(m2d, 
          transform = NULL,
          show.ci = F, 
          show.est = T, 
          show.se = T, 
          show.stat = T,
          show.obs = F,
          show.r2 = F,
          string.stat = "z value",
          string.se = "SE", 
          dv.labels = "Preditors associated with pool mucilage ",
          pred.labels = c("(Intercept)",
                          "Water turbidity (Y/N)",
                          "DO", 
                          "log(PAR)", 
                          "Depth"))

```

Get your plot on gurl!

```{r Plotting FIGS 2 + 3}
## **DO ~ Goop** ##
df_goop<- goop %>%
          drop_na(Goop_Cat)%>%
          group_by(Goop_Cat) %>%
          summarise(sum_tads = sum(Tad_Count), 
                    mean = mean(Tad_Count), #sum_tads/n_pools
                    n_pools = n(), 
                    gross_mean_detect = sum_tads/14) %>%
          ungroup()

##### FIGURE 2A
ggplot(data = df_goop, 
       aes(x = Goop_Cat, y = mean)) + 
geom_bar(width = 1, stat = "identity", color = "white", 
            fill = "#00990c", alpha = 0.6) +
    scale_y_continuous(
    limits = c(-0.02, 1), #so bars dont start in center
    expand = c(0, 0),
    breaks = c(0, 0.2, 0.4, 0.6, 0.8, 1)) +
annotate(geom = "rect", 
           xmin = 0.5, xmax = 4.5, 
           ymin = 0, ymax = 1, 
           fill = "grey", alpha = 0.2)+
geom_segment(x = 1.5, xend = 1.5, 
      y = 0, yend = 0.999, colour = "white", size = 4) + 
  geom_segment(x = 2.5, xend = 2.5, 
      y = 0, yend = 0.999, colour = "white", size = 4) + 
  geom_segment(x = 3.5, xend = 3.5, 
      y = 0, yend = 0.999, colour = "white", size = 4) + 
geom_segment(data = df_goop, 
aes(x = as.numeric(Goop_Cat), xend = as.numeric(Goop_Cat), y = 0, yend = mean), colour = "black", 
size = 0.5, linetype = "dashed") +
geom_point(data = df_goop, 
             aes(x = Goop_Cat, y =mean), 
             shape = 21, 
             fill = "white", 
             size = 3, stroke = 1)+
  xlab("Mucilage level in pool")+
  ylab("Proportion of sampled pools with tadpoles")+
 # coord_cartesian(ylim= c(0,1))+
  labs(tag = "A")+
  theme(text = element_text(size = 20))

##### FIGURE 2B

goop$Goop_Cat<- forcats::fct_relevel(goop$Goop_Cat, c("None", "Low", "Medium", "High"))
df_goop$Goop_Cat<- forcats::fct_relevel(df_goop$Goop_Cat, c("None","Low", "Medium", "High"))

b<- goop%>%
  drop_na(Goop_Cat)%>%
ggplot(aes(y = DO, x = Goop_Cat, colour = Goop_Cat))+
  geom_jitter(height = 0, width = 0.06, size = 2.4, alpha = 0.9, 
              shape = 21, stroke = 1)  + #aes(colour = YNTad)
 # scale_colour_distiller(palette = "Set2")+
  stat_summary(fun.data = mean_cl_boot, 
               geom = "pointrange", 
               fill = "white",
               colour = "black",
               shape = 21,
               size = 0.9)+
    ggdist::stat_halfeye(aes(fill = Goop_Cat),
                      width = 0.3, #width is for dist.
                       adjust = 0.66, #bandwidth for dist
                       #alpha = 0.8, 
                       justification = -0.2, #push dist.
                       #remove slab interval
                       .width = 0, 
                       shape = 16,
                       #fill = "tan",
                       #point_colour = "transparent", 
                       point_alpha = 0,
                       point_interval= median_qi,
                       position= position_nudge(x = 0.1))+
 scale_colour_manual(values = c(
   "#FFD478", "#FFC74E",
   "#FFBA25", "#E49C00"))+   
   scale_fill_manual(values = c(
   "#FFD478", "#FFC74E",
   "#FFBA25", "#E49C00"))+  
  xlab("Mucilage level in pool")+
  ylab("Dissolved oxygen (DO)") + 
  guides(colour = "none", fill = "none")+
  labs(tag = "B") + 
  theme(text = element_text(size = 20))
b 
  
### FIGURE 3A

df_leaf<- goop %>%
          group_by(L_H) %>%
          drop_na()%>%
          summarise(sum_tads = sum(Tad_Count), 
                    mean = mean(Tad_Count), 
                    n_pools = n()) %>%
          ungroup()

ggplot(data = df_leaf, 
       aes(x = L_H, y = mean)) + 
geom_bar(width = 1, stat = "identity", color = "white", 
            fill = "#00990c", alpha = 0.6) +
    scale_y_continuous(
    limits = c(-0.02, 1), #so bars dont start in center
    expand = c(0, 0),
    breaks = c(0, 0.2, 0.4, 0.6, 0.8, 1)) +
annotate(geom = "rect", 
           xmin = 0.5, xmax = 3.5, 
           ymin = 0, ymax = 1, 
           fill = "grey", alpha = 0.2)+
geom_segment(x = 1.5, xend = 1.5, 
      y = 0, yend = 0.999, colour = "white", size = 4) + 
  geom_segment(x = 2.5, xend = 2.5, 
      y = 0, yend = 0.999, colour = "white", size = 4) + 
geom_segment(data = df_leaf, 
aes(x = as.numeric(L_H), xend = as.numeric(L_H), y = 0, yend = mean), colour = "black", 
size = 0.5, linetype = "dashed") +
geom_point(data = df_leaf, 
             aes(x = L_H, y =mean), 
             shape = 21, 
             fill = "white", 
             size = 3, stroke = 1)+
  xlab("Relative leaf height")+
  ylab("Proportion of sampled pools with tadpoles")+
     theme(text = element_text(size = 20))+
  labs(tag = "A")

### FIGURE 3B

ggplot(data = df_leaf, 
       aes(x = L_H, y = mean)) + 
geom_bar(width = 1, stat = "identity", color = "white", 
            fill = "#00990c", alpha = 0.6) +
    scale_y_continuous(
    limits = c(-0.02, 1), #so bars dont start in center
    expand = c(0, 0),
    breaks = c(0, 0.2, 0.4, 0.6, 0.8, 1)) +
annotate(geom = "rect", 
           xmin = 0.5, xmax = 3.5, 
           ymin = 0, ymax = 1, 
           fill = "grey", alpha = 0.2)+
geom_segment(x = 1.5, xend = 1.5, 
      y = 0, yend = 0.999, colour = "white", size = 4) + 
  geom_segment(x = 2.5, xend = 2.5, 
      y = 0, yend = 0.999, colour = "white", size = 4) + 
geom_segment(data = df_leaf, 
aes(x = as.numeric(L_H), xend = as.numeric(L_H), y = 0, yend = mean), colour = "black", 
size = 0.5, linetype = "dashed") +
geom_point(data = df_leaf, 
             aes(x = L_H, y =mean), 
             shape = 21, 
             fill = "white", 
             size = 3, stroke = 1)+
  xlab("Relative leaf height")+
  ylab("Proportion of sampled pools with tadpoles")+
     theme(text = element_text(size = 20))+
  labs(tag = "A")

goop%>%
drop_na(L_H)%>%
ggplot(aes(x = L_H, y = Depth, colour = L_H))+
  geom_jitter(height = 0, width = 0.06, size = 2.4, alpha = 1, 
              shape = 21, stroke = 1)  + #aes(colour = YNTad)
  stat_summary(fun.data = mean_cl_boot, 
               geom = "pointrange", 
               fill = "white",
               colour = "black",
               shape = 21,
               size = 0.9)+
    ggdist::stat_halfeye(aes(fill = L_H),
                      width = 0.3, #width is for dist.
                       adjust = 0.66, #bandwidth for dist
                       alpha = 0.3, 
                       justification = -0.2, #push dist.
                       #remove slab interval
                       .width = 0, 
                       shape = 16,
                       #fill = "tan",
                       #point_colour = "transparent", 
                       point_alpha = 0,
                       point_interval= median_qi,
                       position= position_nudge(x = 0.1))+
  scale_colour_manual(values = c("#FFEF8F", "#BFE360","#6CC19D"))+
  scale_fill_manual(values = c("#FFF4B3", "#D6F489","#C7EFDE"))+
  ylab("Pool depth (cm)")+
  xlab("Relative leaf height")+
  theme(text = element_text(size = 20))+
  labs(tag = "B") 
```








